export const Permissions = {
  CREATE_CHARACTER: "CREATE_CHARACTER",
  DELETE_CHARACTER: "DELETE_CHARACTER",
  UPDATE_CHARACTER: "UPDATE_CHARACTER",
  BAN_ACCOUNT: "BAN_ACCOUNT",
  BAN_CHAT: "BAN_CHAT",
  UNBAN_ACCOUNT: "UNBAN_ACCOUNT",
  UNBAN_CHAT: "UNBAN_CHAT",
  RESTORE_PASSWORD: "RESTORE_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  UPDATE_INVENTORY: "UPDATE_INVENTORY",
  CHANGE_CLASS: "CHANGE_CLASS",
  UPGRADE_SOUL: "UPGRADE_SOUL",
  ADD_CREDITS: "ADD_CREDITS",
  REMOVE_CREDITS: "REMOVE_CREDITS",
};
//subject to changes
